[package]
name = "grapheners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.17.3"
serde_json = "1.0.83"
json = "0.12.4"
url = "2.2.2"